package com.clinicscluster.helper

object ApiContants {

        val errorMsg: String = "please enter your "

        //        const val PREF_base_url = "http://13.71.115.17/my_pms2/mdpapi/"
        const val PREF_base_url = "https://officeintact.com/clinic/api/v1/"
        const val PREF_homepage = "homepage"
        const val PREF_front_service = "front-service"
        const val PREF_login = "login"
        const val PREF_add_appointments = "add-appointments"
        const val PREF_forget_password = "forget-password"
        const val PREF_my_appointments = "my-appointments"
        const val PREF_userregister = "userregister"
        const val PREF_get_clinics = "get-clinics"
        const val PREF_getdoctorsbyclinic = "getdoctorsbyclinic"
        const val PREF_getslotbydoctor = "getslotbydoctor"
        const val PREF_services = "services"
        const val PREF_Msrno = "Msrno"
        const val PREF_Membertype = "Membertype"
        const val PREF_MemberID = "MemberID"
        const val PREF_MemberName = "PREF_MemberName"
        const val PREF_Mobile = "PREF_Mobile"
        const val PREF_TransPass = "PREF_TransPass"
        const val user_code = "user_code"
        const val PREF_IsLogin = "PREF_IsLogin"
        const val PREF_user_image = "PREF_user_image"
        const val PREF_Login_Id = "PREF_Login_Id"
        const val PREF_Login_password = "PREF_Login_password"
        const val PREF_email = "email"
        const val PREF_join_date = "PREF_join_date"
        const val PREF_city = "city"
        const val PREF_state = "state"
        const val PREF_totaldownline = "totaldownline"
        const val PREF_AMOUNT = "Loan_amount"
        const val PREF_totaldirect = "totaldirect"
        const val status1 = "status1"
        const val PREF_device = "PREF_device"
        const val PREF_Address = "PREF_Address"
        const val PREF_Balance = "PREF_Balance"
        const val PREF_operator_code = "PERF_Operoto_code"
        const val PREF_amt = "PREF_amt"
        const val PREF_temp_number = "PREF_temp_number"
        const val PREF_Landmark = "PREF_Landmark"
        const val PREF_CountryCode = "PREF_CountryCode"
        const val PREF_StateId = "PREF_StateId"
        const val PREF_Zip = "PREF_Zip"
        const val PREF_GST_no = "PREF_GST_no"
        const val PREF_F_name = "PREF_F_name"
        const val PREF_L_name = "PREF_L_name"
        const val WhatsAppNumber = "PREF_L_name"
}